### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by Bram91** [processone/xmpp-messenger-ios#1]
Hi there,

I am not able to run pod install without getting a lot of errors.
All I did was a git clone and cd to the Example directory.

Greetings,
Bram.

**Comment by Bram91** [comment]
Analyzing dependencies
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

```
xcodeproj 'path/to/Project.xcodeproj'
```

after I fix that error I get this error:

Brams-Mac-mini:Example bramvangemert$ pod install
Analyzing dependencies
Fetching podspec for `xmpp-messenger-ios` from `../`

[!] Invalid `xmpp-messenger-ios.podspec` file: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  s.homepage         = "https://github.com/<GITHUB_USERNAM...
                             ^
/Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:20: unknown regexp options - gthb
/Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:20: syntax error, unexpected '<'
...        = "https://github.com/<GITHUB_USERNAME>/xmpp-messeng...
...                               ^
/Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:23: syntax error, unexpected '<'
...{ :git => "https://github.com/<GITHUB_USERNAME>/xmpp-messeng...
...                               ^
/Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:28: unknown regexp options - Cla
/Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:28: syntax error, unexpected **arg
  s.source_files = 'Pod/Classes/**/_'
                                  ^
/Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:30: unknown regexp options - At
target of repeat operator is not specified: /_'
  s.resource_bundles = {
    'xmpp-messenger-ios' => ['Pod/
/Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:30: syntax error, unexpected *
    'xmpp-messenger-ios' => ['Pod/Assets/*.png']
                                          ^
/Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:30: unterminated string meets end of file
/Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:30: syntax error, unexpected end-of-input, expecting keyword_end. Updating CocoaPods might fix the issue.

 #  from /Users/bramvangemert/Desktop/test/xmpp-messenger-ios/xmpp-messenger-ios.podspec:20
 #  -------------------------------------------
 #                         DESC

>    s.homepage         = "https://github.com/<GITHUB_USERNAME>/xmpp-messenger-ios"
>  #    s.license          = 'MIT'
>  #  -------------------------------------------

**Comment by baoluo** [comment]
Hello Bram,

The pod is not ready yet, but you can use the classes by hand.

Cheers,

Paul
