### ISSUE TITLE
Obj-C version

### ISSUE THREAD

**Issue by khanhvu161188** [processone/xmpp-messenger-ios#14]
Do we have any version written in Obj-C?
Or do someone convert from Swift to ObjC?

**Comment by baoluo** [comment]
Hello, It's not planned, as Obj-C isn't the future anymore. But you can use this lib within an Objective-C project.

**Comment by khanhvu161188** [comment]
@baoluo tks for quick response sir. Actually i can use swift inside obj-c project but i want to dive deep inside the way we integrate XMPP framework, JSQMessage and other parts . Its helpful for me to understand it in objC but in swift, i'm newbie !

**Comment by baoluo** [comment]
Actually, it's a wrapper around the XMPPFramework, so you can add an Objective-C file, and extend the wrapper for your usage in Objective-C :)
