### ISSUE TITLE
Do we need FMDB package?

### ISSUE THREAD

**Issue by khanhvu161188** [processone/xmpp-messenger-ios#16]
I don't see any code inside xmpp-messenger-ios need FMDB, so can i remove it sir?

**Comment by baoluo** [comment]
Hello @khanhvu161188, FMDB is used within XMPPFramework, so if someone need to use it, it's here. If you don't need it you can delete it.

**Comment by khanhvu161188** [comment]
@baoluo  tks so much sir. I'm newbie on XMPPFramework and still follow some tutorial on CoreData. But i will try with FMDB on Archive Message too!

**Comment by baoluo** [comment]
You're welcome ! For message archiving you can look at OneMessage.swift (xmppCoreDataArchiving)
