### ISSUE TITLE
error: Failed to call designated initializer on NSManagedObject class 'XMPPUserCoreDataStorageObject' 

### ISSUE THREAD

**Issue by orkhanalizade** [processone/xmpp-messenger-ios#2]
When I try to compile my code with your OneChat controllers it prints me the next error:

`error: Failed to call designated initializer on NSManagedObject class 'XMPPUserCoreDataStorageObject'`

in `OneRoster` file

`func managedObjectContext_roster() -> NSManagedObjectContext {
        return OneChat.sharedInstance.xmppRosterStorage!.mainThreadManagedObjectContext
    }`

How can I fix this error?

**Comment by baoluo** [comment]
Hello, I'm currently working on a pod (cocoa pods) to simplify the installation process, so my guess is that the classes are not swift2 ready yet, I'll update the code in the coming week.

**Comment by orkhanalizade** [comment]
@baoluo I write it in Swift 1.2, not in Swift 2

**Comment by baoluo** [comment]
I'll have a look, it should work under Swift 1.2

**Comment by orkhanalizade** [comment]
@baoluo Thanks! how long it will take? 
I thought that it is because of Core Data, it was disabled at the first time, but later I had enabled it, but my error stills. 

Can you help me to solve this error? Thanks in advance!

**Comment by baoluo** [comment]
I'm currently working on the pod, but in the meantime you can try to start a new project with core data enabled by default and then add the classes

**Comment by orkhanalizade** [comment]
I did it from the scratch with the CoreData, but it still gives me the same error. And, in addition, in your example you did not choose initial controller, so my screen is black when it loads. What do you advice?

**Comment by baoluo** [comment]
I'll download the project but I'm using swift 2 so I'll need to update the code before being able to help you

**Comment by orkhanalizade** [comment]
Okay, I solve some problems, but one more question, please. Here is the repository: git@github.com:orkhanalizade/MessengerOneChat.git

I want to ask you, I took your example project, made initial controller as Contacts Navigation Controller. So, when I run my app, I enter credentials and it forward me to OneChat Controller, but it doesn't show me any contacts and when I press on plus icon it crashes with the `Could not cast value of type 'XMPPUserCoreDataStorageObject_XMPPUserCoreDataStorageObject_' (0x7f92dd0063b0) to 'XMPPUserCoreDataStorageObject' (0x10320b248).` error. 

On the other hand, when I made ContactListTableController as initial controller it crashes with the same error.

What do you think about it?

**Comment by baoluo** [comment]
Ok, so it's "working", give me more time to see whats going on

**Comment by orkhanalizade** [comment]
When I try to print `let sections: NSArray? =  OneRoster.buddyList.sections` this, it prints me the next:

`Optional(("<_NSDefaultSectionInfo: 0x7ff6eafbe0d0>"))`

And 

`CoreData: error: Failed to call designated initializer on NSManagedObject class 'XMPPUserCoreDataStorageObject'`

`Could not cast value of type 'XMPPUserCoreDataStorageObject_XMPPUserCoreDataStorageObject_' (0x7ff6eac3b1e0) to 'XMPPUserCoreDataStorageObject' (0x10b156248).`

**Comment by orkhanalizade** [comment]
Did you find any solutions for my problem?
