### ISSUE TITLE
Server for chat client

### ISSUE THREAD

**Issue by jessjpj** [processone/xmpp-messenger-ios#24]
I had gone through the full tutorial to implement a chat client using xmpp-messenger-ios. But what about the server side? I have my own amazon instance and back-end support. So how to store the chat messages in my db?

**Comment by orkhanalizade** [comment]
You can use Openfire or eJabbered on your server-side.

**Comment by baoluo** [comment]
@jessjpj , Please don't use GitHub issues as comment section, Google and Stackoverflow are the place you should look in
