### ISSUE TITLE
Pod errors

### ISSUE THREAD

**Issue by jessjpj** [processone/xmpp-messenger-ios#25]
Hi I am using xcode 7.1 and getting 3 errors when I try to build the project after installing pods. 
1) Include of non-modular header inside framework module 'XMPPFramework.XMPPStream' in XMPPStream.h file
2) Include of non-modular header inside framework module 'XMPPFramework.XMPPLogging' in XMPPLogging.h file
3) Could not build Objective-C module 'XMPPFramework' in OneChat.swift file

**Comment by orkhanalizade** [comment]
Can you share your screenshot? Also, you can upgrade to Xcode 7.2

**Comment by baoluo** [comment]
@jessjpj Check your framework search paths and ALLOW_NON_MODULAR_HEADER Bool

**Comment by nguyenchiencong** [comment]
@baoluo @orkhanalizade Same problem with xcode 7.2. Can you explain a little bit. The integration process seems daunting. Thx

**Comment by baoluo** [comment]
@nguyenchiencong After installation, you should deep clean you Xcode project, that's all

**Comment by nguyenchiencong** [comment]
@baoluo If it were that simple... Anyway I got it working in a different way without cocoapods. I think the documentations and the explanations of this repo should be more explanatory. All the issues closed are closed in a very hurried way, giving me the impression of not wanting to contribute anymore... Just my two cents

**Comment by baoluo** [comment]
Hello @nguyenchiencong, the issues are closed quickly because they are linked to each other, I will provide an updated code on both the repo & cocoa pod, the weird issues you and the other are experimenting are linked to cocoapod's install. If you want to provide a pull request, I'll be pleased to review it !

**Comment by baoluo** [comment]
Hello guys !

I updated the Readme to reflect the changes you have to make !

Xcode 7.X compiler did change, and it doesn't like the modular import.

The solution is to edit 3 files: replace the #import to @import as explained in the readme.

I'll make a pull request to the owner of the XMPPFramework to include those changes so nobody will have to edit the file in the future.

Sorry for the inconvenience, I hope you'll build cool stuff !

Don't be afraid to contribute :)
