### ISSUE TITLE
Even if can not I update from github

### ISSUE THREAD

**Issue by bisoo** [processone/xmpp-messenger-ios#27]
![2015-12-15 3 01 34](https://cloud.githubusercontent.com/assets/15645784/11803311/0bc25f10-a33d-11e5-80a8-d10cf761b4eb.png)
<img width="960" alt="2015-12-15 3 02 42" src="https://cloud.githubusercontent.com/assets/15645784/11803312/0be68598-a33d-11e5-9794-f30acd3afe6f.png">

**Comment by orkhanalizade** [comment]
Do you read my comments carefully? I think, no! Do hard clean `Command + Option + Shift + K`!

**Comment by bisoo** [comment]
yes i do 
We check carefully
Now, I get this error
<img width="960" alt="2015-12-15 4 46 56" src="https://cloud.githubusercontent.com/assets/15645784/11804976/a8d4bbc8-a34b-11e5-9d91-c3993f1f0c3c.png">

Is there an easier way????

**Comment by orkhanalizade** [comment]
@bisoo Paul, close this issue, please.
