### ISSUE TITLE
Not able to integrate xmpp swift messenger in my iOS app

### ISSUE THREAD

**Issue by ektas** [processone/xmpp-messenger-ios#28]
Hi 

I have a create an empty xcode project in xcode7.1.1 with swift 2. I wrote pod 'xmpp-messenger-ios' in my pod file. After installing all the dependencies when I build the project it show errors as "include of non-module header inside framework module" as shown in attached screen shot. This error is not letting me proceed. please help?

<img width="243" alt="screen shot 2015-12-22 at 4 06 25 pm" src="https://cloud.githubusercontent.com/assets/209099/11953403/faa926e4-a8c5-11e5-895a-78e17e2ef201.png">

**Comment by nailgilaziev** [comment]
I have the same problem

**Comment by JavierAlvarezCastillo** [comment]
Change #includes "Something/something2.h" with @include Something

**Comment by nailgilaziev** [comment]
I change:
#import "CocoaAsyncSocket/GCDAsyncSocket.h" to @import CocoaAsyncSocket;
#import "CocoaLumberJack/DDLog.h" to @import CocoaLumberjack; (ps why "j" not capitalized?)

and try to build.
After that same problem in the file JSQSystemSoundPlayer+JSQMessages.h
change too: 
#import <JSQSystemSoundPlayer/JSQSystemSoundPlayer.h> to @import JSQSystemSoundPlayer;
and it is succesfully builded. What the magic? I didn't understand...

@include or @import is the best choice in this situation?

**Comment by orkhanalizade** [comment]
please, search in closed issues too, before opening a new issue. Here you can find the solution: https://github.com/processone/xmpp-messenger-ios/issues/15

**Comment by baoluo** [comment]
Thanks @orkhanalizade, closing this now
