### ISSUE TITLE
error undefined _GCDAsyncSocketManuallyEvaluateTrust

### ISSUE THREAD

**Issue by philipmoniaga** [processone/xmpp-messenger-ios#3]
Hi i tried to build your project and i got this error 

`Undefined symbols for architecture armv7:
  "_GCDAsyncSocketManuallyEvaluateTrust", referenced from:
      xmpp_messenger_ios.OneChat.xmppStream (xmpp_messenger_ios.OneChat)(ObjectiveC.XMPPStream?, willSecureWithSettings : ObjectiveC.NSMutableDictionary?) -> () in OneChat.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I'm using Xcode 7
I have search and don't know how to reproduce it.. Do you have any solution? Thanks

**Comment by baoluo** [comment]
Hello,

You should try to deep clean Xcode (command + alt + shift + K)

Paul

**Comment by Matak99** [comment]
Hey,

I have the same problem and i tried to clean Xcode, but that doesn't help at all!

**Comment by prabakaran-muthusamy** [comment]
Hi,
I'm facing this issue in Xcode 14, Even after clearing the Derived data and clean build folder

<img width="470" alt="Screenshot 2022-10-19 at 1 47 04 PM" src="https://user-images.githubusercontent.com/44673016/196635818-870288b8-5aac-46ed-9e38-69f4070bc779.png">

**Comment by svwalekar** [comment]
I am also getting same issue even after deep clean

**Comment by prabakaran-muthusamy** [comment]
> 

Quite Xcode and reopen again and again, I tried 2 times now it's working for me
