### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by cloudjanak** [processone/xmpp-messenger-ios#31]
![screen shot 2016-01-28 at 4 36 21 pm](https://cloud.githubusercontent.com/assets/7457258/12642671/53fdcaae-c5dd-11e5-8f20-a84a2b2cf731.png)

**Comment by orkhanalizade** [comment]
This issue appears because of the cocoapods repository is old and it did not updated since the last my updates. So, you need to:
1. Check, do you have OneLastActivity.swift file in your Pods -> XMPP folder
2. If not, take this file from this repo and add it.

**Comment by cloudjanak** [comment]
Repo has no file

**Comment by orkhanalizade** [comment]
Are you sure: [OneLastActivity](https://github.com/processone/xmpp-messenger-ios/blob/master/Pod/Classes/OneLastActivity.swift)

**Comment by cloudjanak** [comment]
Repo has file but not able to compile

**Comment by cloudjanak** [comment]
i have added also sir,but still error

**Comment by orkhanalizade** [comment]
Search in closed issues. I described before how to fix it

**Comment by cloudjanak** [comment]
i done all the steps but still issue sir

**Comment by cloudjanak** [comment]
can you please commit updated code?

**Comment by orkhanalizade** [comment]
screenshot please

**Comment by cloudjanak** [comment]
already attached on above.

**Comment by orkhanalizade** [comment]
Read [this issue](https://github.com/processone/xmpp-messenger-ios/issues/26), VERY CAREFULLY! I already answered to it.

**Comment by baoluo** [comment]
Thanks @orkhanalizade , I'm closing this now
