### ISSUE TITLE
unable to compile after the pod install

### ISSUE THREAD

**Issue by arunarya111** [processone/xmpp-messenger-ios#32]
After Pod install my code is not compiling.
Can you please help?
Also tried with a fresh project.
I am using xcode 7 
<img width="1280" alt="screen shot 2016-02-03 at 6 56 24 pm" src="https://cloud.githubusercontent.com/assets/4937841/12783534/325164fe-caa8-11e5-9e4f-1c52578e51e9.png">
<img width="1280" alt="screen shot 2016-02-03 at 6 56 27 pm" src="https://cloud.githubusercontent.com/assets/4937841/12783537/33366b12-caa8-11e5-9760-eaf06eaa6be2.png">
<img width="1280" alt="screen shot 2016-02-03 at 6 56 31 pm" src="https://cloud.githubusercontent.com/assets/4937841/12783533/31c8340e-caa8-11e5-8824-ab7389cb3899.png">

**Comment by orkhanalizade** [comment]
Did you take a look at this [issue](https://github.com/processone/xmpp-messenger-ios/issues/15)?

**Comment by OptimisticMonkey** [comment]
Getting the same issue

**Comment by orkhanalizade** [comment]
@OptimisticMonkey please read carefully the link posted above by me

**Comment by arunarya111** [comment]
@orkhanalizade  i have gone through the post it has 3 approaches i have tried them all but stuck at last step for each.is there a way i can get correct list of steps?

**Comment by OptimisticMonkey** [comment]
I ended up adding the following to the end of the Podfile:

post_install do |installer|
    `rm -rf Pods/Headers/Private`
    `find Pods -regex 'Pods\/.*\.modulemap' -print0 | xargs -0 sed -i '' 's/private header.*//'`
end

**Comment by arunarya111** [comment]
@OptimisticMonkey **this gives me a syntax error 
Should i update cocoapods?**
[!] Invalid `Podfile` file: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
rm -rf Pods/Headers/Private
           ^
/Users/arun/ios/testxmpp/Podfile:8: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
find Pods -regex 'Pods\/._.modulemap' -print0 ...
                  ^
/Users/arun/ios/testxmpp/Podfile:8: syntax error, unexpected tUMINUS_NUM, expecting keyword_do or '{' or '('
..._.modulemap' -print0 | xargs -0 sed -i '' 's/private header...
...                               ^
/Users/arun/ios/testxmpp/Podfile:8: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
...ap' -print0 | xargs -0 sed -i '' 's/private header.*//'
...                               ^. Updating CocoaPods might fix the issue.

**Comment by OptimisticMonkey** [comment]
Did you include all the following:
`post_install do |installer|
rm -rf Pods/Headers/Private
find Pods -regex 'Pods\/.*\.modulemap' -print0 | xargs -0 sed -i '' 's/private header.*//'
end`

**Comment by orkhanalizade** [comment]
I'll check it, soon

**Comment by orkhanalizade** [comment]
@arunarya111 @OptimisticMonkey  I've just downloaded the repository fromGitHub, opened "Example" and on Xcode 7.2.1 it works perfectly. There are some bugs, relative with the OneLastActivity, you can fix these by reading this [issue](https://github.com/processone/xmpp-messenger-ios/issues/26) carefully. I already described how to fix it.

<img width="530" alt="2016-02-05 11 45 24" src="https://cloud.githubusercontent.com/assets/7026025/12840605/3455d9a4-cbfe-11e5-9d27-4c789ff5cc04.png">

**Comment by arunarya111** [comment]
Thanks alot for the help
I ended up upgrading cocoapods adding platform :ios, '8.0' in the begining of the podfile

**Comment by orkhanalizade** [comment]
you're welcome!
