### ISSUE TITLE
Trust problem?

### ISSUE THREAD

**Issue by HitEmUp** [processone/xmpp-messenger-ios#34]
I can't get my connection with my server done! Becouse of trust? 
The objective-c code works fine with my server, so i want to try this swift messanger but it get always:
"Error Domain=kCFStreamErrorDomainSSL Code=-9825 ..."

In my objective-c code i changed this to get it running:
`completionHandler(shouldTrustPeer: true) // Has to be false if SSL is rdy!`
 but in this project the function never triggert...

![bildschirmfoto 2016-02-04 um 20 32 52](https://cloud.githubusercontent.com/assets/10390619/12827354/a757e62e-cb7f-11e5-8f3e-164d71d32696.png)

Some one know whats wrong with it, or me ;)

notice:
And if i changed this to false:
`customCertEvaluation = false;`
i get:
Error Domain=kCFStreamErrorDomainSSL Code=-9807

Dokumentation said:
errSSLPeerBadCert           = -9825,    /\* misc. bad certificate _/
errSSLXCertChainInvalid     = -9807,    /_ invalid certificate chain */

**Comment by baoluo** [comment]
Hello @HitEmUp , this is not a bug, this is a new feature of iSO9, you have to create a safe entry in you application plist to enable the app to communicate with SLL-less servers
