### ISSUE TITLE
 Cannot load module XMPP_Messenger_iOS as xmpp_messenger_ios

### ISSUE THREAD

**Issue by AliYouness** [processone/xmpp-messenger-ios#35]
Dears 

I am facing problem on build the project inder Xcode 7.2.1 and Swift 2.1  the problem is Can not load module XMPP_Messenger_iOS as xmpp_messenger_ios . but when i cleam the  drived data folder and force Quit xcode  then rebuild again it work as expected .

**Comment by julylinan** [comment]
met the same problem when running the example, does anyone know how to deal with it? Thanks

**Comment by gf3** [comment]
:+1:

**Comment by baoluo** [comment]
Hello all, we are aware of this "issue", but like you said, a deep clean is enough to get rid of it, for the moment it will stay as-it.

**Comment by Matak99** [comment]
I've tried to clean it eleven times now and I get the error again and again and again?

**Comment by rihanmahraotra** [comment]
Hie  #Matak99 
I also faced this issue but by deep clean command+alt+shift+k I resolved it.
If again you are facing this problem again try to update your xcode+swift and cocospods.

**Comment by Matak99** [comment]
everything is up to date. A deep clean fixes the error one time out of ten :/

**Comment by hirenpanchal1608** [comment]
I am also getting this issue.
After deep clean, once it build succeeded, but again same issue is happening.
