### ISSUE TITLE
Include of non-modular header inside framework module 'XMPPFramework.XMPPStream'

### ISSUE THREAD

**Issue by LinkeyWork** [processone/xmpp-messenger-ios#36]
Steps:
1 - Creating new project.
2 - Adding pod to pods file

and I have an error on "XMPPStream" interface.
# import "CocoaAsyncSocket/GCDAsyncSocket.h"

**I tried --deep clean Xcode (command+alt+shift+k)

**Comment by LinkeyWork** [comment]
Problem solved by updating my cocoapods gem

**Comment by shivang2902** [comment]
Getting problem at Line 5 - #import "CocoaAsyncSocket/GCDAsyncSocket.h"
Tried deep clean also , and my podfile is also Ok. Please help me out on this one @baoluo
