### ISSUE TITLE
Send photo via XMPPFramework

### ISSUE THREAD

**Issue by quangpc-zz** [processone/xmpp-messenger-ios#37]
Could you please update example for sending photo via XMPPFramework.
Thank you

**Comment by baoluo** [comment]
Hello @quangpc, sending a picture is possible, just use the classic xmpp data transfer to send it.

**Comment by hussain3152** [comment]
Sending Image using the same way still unable to send the image.
Please help us here.

**Here is how we are sending image.**

        let data = UIImagePNGRepresentation(self.imageSelectedOrTaken)
        let imageStr = data?.base64EncodedString()
        
        let body = DDXMLElement.element(withName: "body") as! DDXMLElement
        let messageID = OneChat.sharedInstance.xmppStream?.generateUUID()
        let imageAttachement = DDXMLElement.element(withName: "attachment", stringValue: imageStr!) as! DDXMLElement
        
        let message = DDXMLElement.element(withName: "message") as! DDXMLElement
        message.addAttribute(withName: "type", stringValue: "chat")
        message.addAttribute(withName: "id", stringValue: messageID!)
        message.addAttribute(withName: "to", stringValue: (recipient?.jid.full())!)
        message.addChild(body)
        message.addChild(imageAttachement)
        
        OneChat.sharedInstance.xmppStream?.send(message)

Any help provided will be appreciated.

Thanks
