### ISSUE TITLE
in swift demo tree.h file is not found how to solve it

### ISSUE THREAD

**Issue by hirengohel** [processone/xmpp-messenger-ios#38]
![screen shot 2016-03-05 at 2 40 57 pm](https://cloud.githubusercontent.com/assets/6431786/13546837/621fe0c0-e2e0-11e5-9a48-45a3232bbfb8.png)

**Comment by baoluo** [comment]
Hello @hirengohel , You should check the tree.h path on your computer, it may be different for some reason, are you using Xcode-beta app ?

**Comment by donirn** [comment]
I found the same problem, tree.h is not found.
And the "import xmpp_messenger_ios" in AppDelegate.swift is not found as well stated "No such module"

I used XCode 7.3.1

**Comment by donirn** [comment]
Problem solved by moving the Xcode.app to Applications folder.
