### ISSUE TITLE
Running demo file shows error.

### ISSUE THREAD

**Issue by gabhisekdev** [processone/xmpp-messenger-ios#42]
I was about to implement your framework. Before that I wanted to check the demo functionality of the framework, but on building it shows an error in ChatViewController.swift - as _"use of unresolved identifier    OneLastActivity"_

```
OneLastActivity.sendLastActivityQueryToJID((recipient.jidStr), sender: OneChat.sharedInstance.xmppLastActivity) { (response, forJID, error) -> Void in
                        let lastActivityResponse = OneLastActivity.sharedInstance.getLastActivityFrom((response?.lastActivitySeconds())!)

                        self.userDetails = OneLastActivity.sharedInstance.addLastActivityLabelToNavigationBar(lastActivityResponse, displayName: recipient.displayName)
                        self.navigationController!.view.addSubview(self.userDetails!)

                        if (self.userDetails != nil) {
                                self.navigationItem.title = ""
                        }
                    }
```

So any idea about this?

**Comment by baoluo** [comment]
Hello @GABHISEKBUNTY , You should use the pod instead of the zip file, the code isn't synchronized, OneLastActivity doesn't exist anymore

**Comment by mremond** [comment]
@baoluo I commented out that section of the code in commit https://github.com/processone/xmpp-messenger-ios/commit/98ca2e93dae5a1f962d6c211cf90a2935291ddad 

What that the right thing ? Should code be deleted ?

**Comment by baoluo** [comment]
@mremond Thanks, I will Update the code soon, the OneLastActivity file was requested by an user (Pull request) but it wan't properly implemented, so the file was deleted in the 'pod' version of the repo.
