### ISSUE TITLE
Several issues while uploading it as a Pod.

### ISSUE THREAD

**Issue by gabhisekdev** [processone/xmpp-messenger-ios#43]
I tried to get the framework installed via cocoapods, But now I m running into several problems eg. No such module, cannot build objective C framework as.... 

You can all view them on running the project I have attached herewith.
[chatSwift.zip](https://github.com/processone/xmpp-messenger-ios/files/180671/chatSwift.zip)

**Comment by capkin90** [comment]
after executing the pod install command and starting the swift project i get the same following issues:
- no such modul 'xmpp-messenger-ios' in the AppDelegate.swift class
- 'CocoaAsyncSocket/GCDAsyncSocket.h' file not found in the XMPPStream.h file
- Could not build Objective-C module 'XMPPFramework' in the OneChat.swift class
- ...

how i can fix the issues?

**Comment by baoluo** [comment]
Hello @GABHISEKBUNTY , @capkin90 I already explained how to fix theses issues in other thread on Github, I'll upload an update soon, but for now what you need to do is put the module.modulemap file path in your target's "header search path", and you'll get rid of theses errors

**Comment by ashiqsulaiman** [comment]
after including the xmpp_messenger_ios i am getting errors after cleaning. it says include of non modular header inside framework module. i changed allow non modular includes in framework modules to yes in the build settings. Also changed target membership to public, it still doesn't help.

**Comment by baoluo** [comment]
Hello @ashiqsulaiman, Like I said on another open issue, I'll update the repo to get rid of theses errors

**Comment by ashiqsulaiman** [comment]
@baoluo Thank you :)

**Comment by baoluo** [comment]
Hello guys !

I updated the Readme to reflect the changes you have to make !

Xcode 7.X compiler did change, and it doesn't like the modular import.

The solution is to edit 3 files: replace the #import to @import as explained in the readme.

I'll make a pull request to the owner of the XMPPFramework to include those changes so nobody will have to edit the file in the future.

Sorry for the inconvenience, I hope you'll build cool stuff !

Don't be afraid to contribute :)
