### ISSUE TITLE
Getting a lot of errors after installing via cocoapods

### ISSUE THREAD

**Issue by RollingGoron** [processone/xmpp-messenger-ios#44]
I'm trying to follow your guide and running into a ton of compiling errors after I add "import xmpp_messenger_ios" to my AppDelegate. I'm running latest verions of Xcode 7.3. Can you update your guide on how to avoid these problems? 

Errors: Include of non-modular header inside framework module 'XMPPFramework.XMPPStream'
Could not build Objective-C module 'XMPPFramework'

Thanks!

**Comment by Usman11223344** [comment]
I have successfully integrated the XMPPFramework through pod but when I try to build a project I found a error. I have searched alot but does not found anything. Kindly help me out to fix this issue.
![screen shot 2016-04-18 at 1 19 42 pm](https://cloud.githubusercontent.com/assets/18526549/14597845/a77aee76-0568-11e6-95a0-db8d814c2217.png)

**Comment by baoluo** [comment]
Hello guys !

I updated the Readme to reflect the changes you have to make !

Xcode 7.X compiler did change, and it doesn't like the modular import.

The solution is to edit 3 files: replace the #import to @import as explained in the readme.

I'll make a pull request to the owner of the XMPPFramework to include those changes so nobody will have to edit the file in the future.

Sorry for the inconvenience, I hope you'll build cool stuff !

Don't be afraid to contribute :)
