### ISSUE TITLE
How to create database using FMDB?

### ISSUE THREAD

**Issue by Koutenshidatshu** [processone/xmpp-messenger-ios#47]
Hi, i want create database using FMDB, but i can't import FMDB in swift
error message : could not build objective-c module 'FMDB'
and how to update FMDB pods? this version its outdate
Thanks

**Comment by baoluo** [comment]
@Koutenshidatshu, if you can't import FMDB in swift you'll have to make a specific module map file or a bridging header to be able to do so. This is not an issue related to this project, so I'm closing this.
