### ISSUE TITLE
Connection to the server

### ISSUE THREAD

**Issue by aitbaali** [processone/xmpp-messenger-ios#48]
any documentation / examples about the connection to XMPP server

**Comment by baoluo** [comment]
Hello @aitbaali, there is documentation on SO, or other places. Github issues that doesn't relate to code aren't allowed here, so I'm closing this.

**Comment by aitbaali** [comment]
Hello Paul,

I'll do that,
and what about this issue "
https://github.com/processone/xmpp-messenger-ios/issues/40"

2016-05-10 0:34 GMT+01:00 Paul Lemaire notifications@github.com:

> Hello @aitbaali https://github.com/aitbaali, there is documentation on
> SO, or other places. Github issues that doesn't relate to code aren't
> allowed here, so I'm closing this.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/processone/xmpp-messenger-ios/issues/48#issuecomment-218020351

## 

_A.Abderrahmane(+212) 0642 246 504_
