### ISSUE TITLE
ChatViewController throw error

### ISSUE THREAD

**Issue by LacieNat** [processone/xmpp-messenger-ios#49]
Hello,

After following the tutorial, I reached an error in the ChatViewController viewDidLoad function after running. Not sure what is the reason. Here is the function

```
 override func viewDidLoad() {
        OneMessage.sharedInstance.delegate = self

        if OneChat.sharedInstance.isConnected() {
            self.senderId = OneChat.sharedInstance.xmppStream?.myJID.bare()
            self.senderDisplayName = OneChat.sharedInstance.xmppStream?.myJID.bare()
        }
        self.inputToolbar!.contentView!.leftBarButtonItem!.hidden = true
        self.collectionView!.collectionViewLayout.springinessEnabled = true
    }
```

and the error is fatal error: unexpectedly found nil while unwrapping an Optional value

Are there any steps that I'm missing?
Thanks!

**Comment by baoluo** [comment]
@LacieNat Could you tell me where the errors was ? It may on the collectionView, it wasn't already in the stack so when you try to access the collectionViewLayout.springinessEnabled on it it crashed.
