### ISSUE TITLE
Xcode Crash on Break Point and Print statements not working

### ISSUE THREAD

**Issue by mwaqasbhati** [processone/xmpp-messenger-ios#53]
I have downloaded your repo. when I apply any breakpoint in Xcode then it crashes on every single breakpoint and also when I try to print any thing then it did not show any output on console. I have tried a lot of solutions on internet but nothing is helping.By the way I am using latest xcode 7.3.1

Any help would be much appreciated..thanks

**Comment by baoluo** [comment]
Hello @mwaqasbhati , It looks like your Xcode is not holding the breakpoint properly, try to reboot your mac, clean you Xcode, and try again.
