### ISSUE TITLE
The Rosters and chat data doesn't persist. After termination or crash the app doesn't show any buddy list or previous chats.

### ISSUE THREAD

**Issue by hemant3370** [processone/xmpp-messenger-ios#54]
![screen shot 2016-07-14 at 6 35 21 pm](https://cloud.githubusercontent.com/assets/2473538/16840344/cbb35972-49f1-11e6-8af2-687519a54d99.png)
And please explain the double coredata model files.

**Comment by baoluo** [comment]
There is a typo, you may I done /  something may gone wrong at some point, you can try to pod deintegrate + pod install again to get rid of this
