### ISSUE TITLE
Include of non-modular header inside framework module 'XMPPFramework.XMPPLogging' 

### ISSUE THREAD

**Issue by shivang2902** [processone/xmpp-messenger-ios#56]
Facing issue at Line 62 #import "CocoaLumberJack/DDLog.h"
Please help me on that , need to kick off with the project @baoluo

**Comment by shivang2902** [comment]
![screen shot 2016-07-25 at 1 10 50 pm](https://cloud.githubusercontent.com/assets/18008508/17093840/47fbfa3c-5269-11e6-8864-2b499b246c79.png)

**Comment by baoluo** [comment]
Please @shivang2902 , look at the readme before opening an issue
