### ISSUE TITLE
XEP-0313 support

### ISSUE THREAD

**Issue by nguyenchiencong** [processone/xmpp-messenger-ios#57]
Is there any plan to support XEP-0313? because XEP-0136 seems to be deprecated.

Best,

**Comment by baoluo** [comment]
Hello, the support for  XEP-0313 is not a question here, but in the XMPPFramework directly !

**Comment by nguyenchiencong** [comment]
They have added support for XEP-0313. Can update the framework here?
Thanks

**Comment by baoluo** [comment]
I can't do it here, it must be done in the XMPPFramework github page
