### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: storage != nil'

### ISSUE THREAD

**Issue by chetansrm** [processone/xmpp-messenger-ios#58]
I have need to addUser  in roster and addUser function is in xmppRoster.m class so I need to create object of xmppRoster by writing xmppRoster() but whenever this method(xmppRoster()) runs its gives the error 
"Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: storage != nil'"
So may I get the solution.

**Comment by baoluo** [comment]
Hello @chetansrm, You have to specify an XMPPRosterStorage to the xmppRoster before using it. This is not related to the project, so i'm closing it.

**Comment by chetansrm** [comment]
Hie #baoluo Thanks it worked for me.

**Comment by baoluo** [comment]
Nice to hear :)

**Comment by BynryGit** [comment]
it also worked for me, Thanks
