### ISSUE TITLE
Do we have any enhancements for Group chat ?

### ISSUE THREAD

**Issue by aadilkeshwani90** [processone/xmpp-messenger-ios#59]
Can you brief me how we can implement group chat here ? Also do we need to change andy classes ? 

Sorry to report it as issue but i didn't find any other way to raise this question

**Comment by baoluo** [comment]
Hello @aadilkeshwani90 You are right it's not an issue so i'll close this right now, I will accept with great pleasure a pull request with the feature, you'll need to create a new class and provide some "user friendly" functions to add / remove users
