### ISSUE TITLE
Unable to receive presence

### ISSUE THREAD

**Issue by rihanmahraotra** [processone/xmpp-messenger-ios#60]
I am creating a chating by xmpp protocol. I want to send the request to user so that they could begin to chat. Firstly I am adding user to roster and subscribing user by the following line of code 
     obj.addUser(xjid, withNickname: "new_user")

```
    obj.subscribePresenceToUser(xjid) //here xjid is well defined
```

So now i need to receive the presence and accept the presence to get the JID of the user who have sent the friend request can be achieved by [presence from] but when I  print these  things to verify  

//   NSString *presenceFromUser = [presence from] ;

// NSString *presenceType = [presence type];

//     NSLog(@"Your name is %@", presenceFromUser);

//      NSLog(@"Sender name is %@", presenceType);

->presenceFromUser is same by which I am login currently  and presenceType is always "available".

```
 According to me it should be
```

->presenceFromUser should be "userJidWhoSentTheRequest@localhost"

->presenceType should be "Subscribe"

**Comment by rihanmahraotra** [comment]
I am unable add any user to the roster
I used addUser() func  but there is no change in the roster.
And when I remove  user from roster then user is removed till app run if I run it again the removed user is again in the roster.
SO what to do ?

**Comment by baoluo** [comment]
Hello @rihanmahraotra, You seems to be new to XMPPFramework, so you should see on StackOverflow if you need any help, you can also checkout the example of this project, to see how I did it. (This is not an issue, I'm closing it)
