### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by chatarveer** [processone/xmpp-messenger-ios#63]
I am facing 

`fatal error: unexpectedly found nil while unwrapping an Optional value
`

at many lines in your library. I have latest xcode 7.3, and I also did convert to swift latest. However still I am getting. 

For example

```
public func isConnected() -> Bool {
        return xmppStream!.isConnected() //here its crashing, 
    }

I did like this

public func isConnected() -> Bool {
        if let boolValue:Bool = xmppStream!.isConnected() {
            return boolValue
        }else {
            return false
        }
    }
```

Can you see what is wrong in code?

**Comment by baoluo** [comment]
@veerdeveloper Yes I seen, you force unwrap an optional value, which can be nil, so it crashes when it is. You should use xmppStream?.isConnected()

**Comment by veerdeveloper** [comment]
Can I update your code and submit to you Sir?

**Comment by baoluo** [comment]
@veerdeveloper Did it solve you're issue ?

**Comment by chatarveer** [comment]
Yes, I solved that issue. Thanks
Regards
Veer Suthar
Senior Mobile Applications Engineer
